# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: sortir_user
  MYSQL_PASSWORD: sortir_user
  MYSQL_DATABASE: sortir
  DB_HOST: mysql

test:
  stage: test
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
  script:
    #- yarn install --pure-lockfile
    - composer install
    - cp .env.ci .env
    - php bin/console doctrine:migrations:migrate
    - php bin/console doctrine:fixtures:load
    #- php artisan key:generate
    #- php artisan migrate:refresh --seed
    #- ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
