# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: sortir_user
  MYSQL_PASSWORD: sortir_user
  MYSQL_DATABASE: sortir
  DB_HOST: mysql
stages:
  - deploy
  - test
  
deploy:
  stage: deploy
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master --force
    
test:
  stage: test
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
  script:
    #- yarn install --pure-lockfile
    - composer install
    - cp .env.ci .env
    - php bin/console doctrine:migrations:migrate
    - php bin/console doctrine:fixtures:load
    - php bin/phpunit
    #- php artisan key:generate
    #- php artisan migrate:refresh --seed
    #- ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr

